spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/capston
    driver-class-name: org.mariadb.jdbc.Driver
    username: CAP
    password: cap1234
  jpa:

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
      open-in-view: false

  security:
    user:
      name: user
      password: 1111

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace